"""
cicd_generator.py
-----------------
Generates CI/CD workflow YAML files for automated test execution.

Supports:
  - GitHub Actions (pytest / playwright / selenium)
"""

from typing import List, Dict, Any
from logger import get_logger

logger = get_logger("CICDGenerator")


class CICDGenerator:
    """
    Generates CI/CD pipeline configuration for automated QA execution.
    Currently supports GitHub Actions YAML for Pytest, Playwright, and Selenium.
    """

    def generate_github_actions(
        self,
        test_cases: List[Dict[str, Any]],
        framework: str = "pytest",
        python_version: str = "3.11",
        branch: str = "main",
    ) -> str:
        """
        Generate a GitHub Actions workflow YAML for the given test framework.

        Args:
            test_cases:      List of test case dicts (used to derive module names for test tags).
            framework:       'pytest', 'playwright', or 'selenium'
            python_version:  Python version string (default '3.11')
            branch:          Branch to trigger CI on (default 'main')

        Returns:
            YAML string for .github/workflows/qa.yml
        """
        fw = framework.lower().strip()
        modules = sorted(set(tc.get("module", "General") for tc in test_cases)) if test_cases else ["All"]
        module_hint = ", ".join(modules[:5]) + ("..." if len(modules) > 5 else "")

        header = f"""\
# ══════════════════════════════════════════════════════════════════════
# GitHub Actions CI/CD Workflow — Auto-Generated by AI QA Platform
# Framework : {framework.title()}
# Modules   : {module_hint or 'All'}
# Generated : Auto
# ══════════════════════════════════════════════════════════════════════

name: QA Automated Test Suite

on:
  push:
    branches: [ "{branch}" ]
  pull_request:
    branches: [ "{branch}" ]
  schedule:
    - cron: '0 2 * * *'   # Nightly run at 02:00 UTC

jobs:
"""

        if fw == "pytest":
            body = f"""\
  pytest-suite:
    name: Run Pytest QA Suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["{python_version}"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{{{ matrix.python-version }}}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{{{ matrix.python-version }}}}
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html pytest-cov

      - name: Run QA Test Suite
        run: |
          pytest tests/ \\
            --html=reports/qa_report.html \\
            --self-contained-html \\
            --cov=. \\
            --cov-report=html:reports/coverage_html \\
            --cov-fail-under=65 \\
            -v

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-test-report
          path: reports/
          retention-days: 30
"""
        elif fw == "playwright":
            body = f"""\
  playwright-suite:
    name: Run Playwright UI Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-playwright
          playwright install chromium --with-deps

      - name: Run Playwright Tests
        run: |
          pytest tests/playwright/ \\
            --browser chromium \\
            --screenshot=only-on-failure \\
            --video=retain-on-failure \\
            --output=playwright-results \\
            -v

      - name: Upload Playwright Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-results/
          retention-days: 30
"""
        else:  # selenium
            body = f"""\
  selenium-suite:
    name: Run Selenium WebDriver Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"
          cache: 'pip'

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager pytest pytest-html

      - name: Run Selenium Tests
        env:
          DISPLAY: ':99'
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          pytest tests/selenium/ \\
            --html=reports/selenium_report.html \\
            --self-contained-html \\
            -v

      - name: Upload Selenium Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-report
          path: reports/
          retention-days: 30
"""

        workflow = header + body
        logger.info(f"Generated GitHub Actions YAML for {framework} ({len(workflow)} chars).")
        return workflow

    def get_supported_frameworks(self) -> List[str]:
        """Returns the list of supported CI/CD frameworks."""
        return ["pytest", "playwright", "selenium"]
